package com.ihdyo.smarthome.utils

object Const {
    const val WEB_CLIENT_ID = "113846780678-po05116d6nmrhmajp36njisbgd51qnm0.apps.googleusercontent.com"
    const val RC_SIGN_IN = 1

    const val ARG_FORGOT_PASSWORD = "forgotPassword"
    const val ARG_CHANGE_USERNAME = "changeUsername"
    const val ARG_CHECK_EMAIL = "checkEmail"
    const val ARG_CHANGE_EMAIL = "changeEmail"
    const val ARG_RECHECK_EMAIL = "recheckEmail"
    const val ARG_CHECK_PASSWORD = "checkPassword"
    const val ARG_CHANGE_PASSWORD = "changePassword"
    const val ARG_RECHECK_PASSWORD = "recheckPassword"

    const val SHARED_PREFERENCES = "AppPreferences"
    const val DEFAULT = "default"
    const val PUSH_NOTIFICATION = "pushNotification"
    const val SUBSCRIBE_NEWSLETTER = "subscribeNewsletter"
    const val DYNAMIC_COLOR = "dynamicColor"
    const val THEME_SELECTED = "themeUsed"
    const val THEME_LIGHT = "themeLight"
    const val THEME_DARK = "themeDark"
    const val LANGUAGE_SELECTED = "languageSelected"
    const val LANGUAGE_ENGLISH = "languageEnglish"
    const val LANGUAGE_INDONESIA = "languageIndonesia"
    const val LANGUAGE_JAVANESE = "languageJavanese"
    const val LANGUAGE_DEFAULT = "languageDefault"

    const val LOCALE_ENGLISH = "en"
    const val LOCALE_INDONESIA = "in"
    const val LOCALE_JAVANESE = "jv"

    const val COLLECTION_USERS = "users"
    const val COLLECTION_ROOMS = "rooms"
    const val COLLECTION_ENVIRONMENTS = "environments"
    const val COLLECTION_LAMPS = "lamps"
    const val FIELD_USER_NAME = "userName"
    const val FIELD_LAMP_IS_AUTOMATIC_ON = "lampIsAutomaticOn"
    const val FIELD_LAMP_IS_POWER_ON = "lampIsPowerOn"
    const val FIELD_LAMP_BRIGHTNESS = "lampBrightness"
    const val FIELD_LAMP_RUNTIME = "lampRuntime"
    const val FIELD_LAMP_SELECTED_MODE = "lampSelectedMode"
    const val FIELD_LAMP_SCHEDULE = "lampSchedule"
    const val MAP_FIELD_SCHEDULE_FROM = "scheduleFrom"
    const val MAP_FIELD_SCHEDULE_TO = "scheduleTo"
    const val LAMP_SELECTED_MODE_AUTOMATIC = "automatic"
    const val LAMP_SELECTED_MODE_MANUAL = "manual"
    const val LAMP_SELECTED_MODE_SCHEDULE = "schedule"
}